// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://veulufxdgfxnoybriint.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZldWx1ZnhkZ2Z4bm95YnJpaW50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjI2MTYsImV4cCI6MjA3MjczODYxNn0.RMZbkADFcOT4fbLz7VS8KYJq6T7CiL6eTIJdUQ-QFK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});